version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/parser"
    versions:
    - 7.13.16
  - dependency-name: "@babel/traverse"
    versions:
    - 7.12.13
    - 7.13.0
    - 7.13.15
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.15.2
    - 4.16.1
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.15.1
  - dependency-name: "@types/babel__traverse"
    versions:
    - 7.11.0
- package-ecosystem: npm
  directory: "/packages/resugar-codemod-calls-spread"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/packages/resugar-codemod-declarations-block-scope"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/packages/resugar-codemod-functions-arrow"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/packages/resugar-codemod-modules-commonjs"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/packages/resugar-codemod-objects-concise"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
