sudo: false
language: node_js
cache: yarn
node_js:
  - '9'
  - '8'
  - '6'
  - '4'
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - yarn semantic-release
  - yarn ts-node script/update-website.ts
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
