#!/usr/bin/env node

const rollup = require('rollup').rollup;
const babel = require('rollup-plugin-babel');
const npm = require('rollup-plugin-npm');
const commonjs = require('rollup-plugin-commonjs');
const json = require('rollup-plugin-json');

function jsnextPlugin(packages) {
  return {
    resolveId(importee, importer) {
      if (packages.indexOf(importee) >= 0) {
        return npmInstance.resolveId(`${importee}-jsnext`, importer);
      }
    }
  };
}

const npmInstance = npm({ jsnext: true });

rollup(
  {
    entry: 'src/esnext.js',
    plugins: [
      jsnextPlugin(['assert']),
      json(),
      babel(),
      commonjs({
        include: 'node_modules/**'
      }),
      npmInstance
    ]
  }
).then(
  bundle => bundle.write({ dest: 'esnext.js', format: 'umd', moduleName: 'esnext' })
).catch(
  err => console.error(err.stack)
);
